travis:
  secure:
    BINSTAR_TOKEN: WIHbsrA4A3NdzJSHwnWJBdKsRJ+VHC/gVnA7BJ9WzScWOxqGF9xv0y/h7L3XP2PlWUl8RuK1filCjBMpD6gMsluSK/ydtErk43UVd8ITiULmhi1FNIJk4BKEhYbdIblNxTr6pBKbFKNi2dLtJ1dfbwrkgnNfMcEO8BAj5xLBI3ZQFkDs0wtrO8f5os+AwYAq7SCTeE9TLQy+ElXXbeLwX4n6hgoU6MuZve6+7Yz8i+HnbzPVoDPI75taPWiesh9TjPG0zPjtQ5YNCSujpEroDwV5ObC9bJUgYMMlm97ha3RvEEl6FCw5EYSrdyBr6aoaGAntoxo+OxwdT5yLyW9vlK7nGV71QQDTzgnTY5ETbrtHn+2wmz/n7/fq/UayxWK82y+wOjNbQqVguGVKAep+0GJaYIfVzN/ZB3YkOG4SASOw1FJTXD0lcMm+lRn6jSWfM9uqRKiCDJYrkJlVftcnd4Zng0ROB36YQudLb19S4340pbGCNBiYo0t4ZTKrIR6xc+av6NpvOkP3jz8qtRXnBusRanhIQJdS5JARVwX0BdifwI9VJcJQpKcwfMBAiiAX1o7Pb6CiaPH8sxRFKg2glfnKuPgWBStK8vxdkad4yF+tcTHSLig2KLgurG35IjbylpmiHO8uJjc/f61w3coiwbD7IoU33kIrSwIt22NewTI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
