appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Cbe8nnKcxgUgSwJdPfqTr/EpK+xjC9obIzM/F3JTg43PmIa/1QtD7rV8pVF/pEGWfzaIswXEwkBXawQH8UfvIDcN+QUv1W/iNwpCX48QFKI/Qr3ZVzJ0PRA5xt+zdmXZBK1K+3ZuN6LSPqQhxIHh4BaubFDFql6eC9uIt228OQorz8n/zRJh/79bmix5WoiHywQqz3Iu/DbOM1SMq0wOQGzwo/SIaRxQ9ARgPE2kZlhZjoxbCTtOPWTkv1CLF9Ru44AVWdE6VSZ98ggDp18Bz0Q9/dKyRgWgkJI0N8bG2Swf91hIPHuz89xKzoViSpq8FoaWSzh74eklMfAlYpz72KPVYeCTvzmm7yOlFAoym6njC/gwh7JXS0aZZcDKvZREE40LxhXj0US3A63aUCjOgucNpnODlJiKecdbtPdOyJ7Eix3J7E8RXeWzcSoo0iTUwxGlDaVcchLsyqPqpBE1hnEdgE4fOXv+acb9qEBLjeryL9zWpzurJpcANc1HcXEl7VeyZVTVxUAj1p9Q077YnyGUXrpwsuJKtONqZ1Fa/FaqhS3V1fJcIge94r54OlJeVo35A/5Skcp6ZHEQCREyGGYlh1t2/0vVd7FYXbNRxtxyIilx3uzvmUojFXPME0XQgLGYlqrm96ZS57yC9SN29TCRdMX4If38hZWnCK68huI=}
