travis:
  secure:
    BINSTAR_TOKEN: ju3Qb2N/DvlEdmhwxC0UzVXup66KNZABxaYTzkoHoipKl+IJC5HDgw7f9hGGL+JfIWnWHdaRHD5nVuvK7v5Ms0DmMeiQUxisxnISTdKi29JPd0fjednC1KqOyY0+E7IgA92BeYKgfBMCxmp4tg4LnZ9BBg7IXefE+lSb/gI/mjj3yUnOGDzQ77CnjWO2E2g+8LHQv8zAXi3Oopwb1wlPDoi/U0SGHCzgrX7oOBrmkBT4MpZ0vdAeLWnyrU+CZpwO2SND2cCSbC193b0JIIc/PMIe5CwD58ZboFWwUtxOibfk88Dxwhh2NXCautjlzuEOqFt01Id+0GAXOWwprQ0GahldfXChlKM/gz1zq04RXHnLToKLUoXRTZBKDfz+ocFyq9jF8nI9U6vPB48kwyxqGw48N0rZgrcaaDb0QjckQ/IWjQ400JloOgzlF3mq5lV4E5d+movEsdN/X/Ybfp433EhtHKA4+Cw5ksLYeGFJc2Xg4cBPuKHQGceY5esp8AMB8C/bqz6B8THzqnUwds0/Vm73GSDVZVxlbGTSw2VytSSfC9lRUpzNj3Wh1WTg6YtWZ5AofaTYAobSViwauwKi3VWpsYlITQx6pVSixn3cviw69ShNZ7w8ftCBZ9fsZZI69ld9P6ZWq++aY6u9GLPlhMHI5q0PWogXr5UMwjk72TE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
